### ISSUE TITLE
Possible incorrect audio frequencies (or error in documentation?)

### ISSUE THREAD

**Issue by MJoergen** [jotego/jt51#10]
In the file "ym2151_app_notes.pdf" on page 7 it is stated that setting the Key Code register to 0x4A generates a frequency of 440 Hz. This is in agreement with Figure 2.4 on page 18, where a maximal output frequency of 4186 Hz is mentioned.

However, the implementation in this repository instead generates 220 Hz with a Key Code of 0x4A. And a maximal frequency of 2093 Hz with a Key Code of 0x7E. So it appears the frequencies in this implementation are too low by a factor of 2 compared to the documentation.

I don't have access to a real YM2151 chip, so I don't know whether this is an error in the implementation or in the documentation. Furthermore, the YM2151 emulator in https://github.com/mamedev/mame appears to agree with this implementation.

It could also be an error in the test stimuli I generate, however I'm pretty sure I've done it correctly:
* I'm stimulating the module jt51 with cen=constant 1, and with cen_p1 alternating 0 and 1.
* I'm clocking clk at 3.579545 MHz.
* I've verified that the timing of the Attack phase is correct: Setting the key code to 0x7A and the attack rate to 0x0C gives a 0-100% attack time of 142 ms, which agrees with the documentation (page 20, rate = "6 3").

Is there something I have misunderstood? Is there an error in the chip documentation?

**Comment by jotego** [comment]
Hi,

I don't think the frequencies are wrong because JT51 has already got some public exposure (see [here](https://www.youtube.com/watch?v=IHF96HX4mK8&t=362s)) and no one has reported a pitch error.

The manual can be a bit misleading at times. Also check that you haven't set your clock frequency wrong in the test bench.

Thank you for using JT51.

**Comment by MJoergen** [comment]
Thank you for your reply. I just wanted to add some more details, where I'm using the verilator scripts for testing, rather than my own test bench. The results are the same.

If we assume the jt51 works, i.e. produces the same output as the real chip, then perhaps there is an error in the documentation? Or in my interpretation of the documentation?

Anyway, I've attached a very short VGM file that generates first a sequence with constant envelope, and then a sequence with a slow attack rate. The corresponding .jtt file is as follows:
```
$020,C7
$080,1F
$0A0,00
$0E0,FF
$028,7A # Key on
$060,00
$008,08
wait 9771 # 0.185737 s
$008,00
wait 9771 # 0.371474 s
$080,0C
$0A0,1F
$008,08
wait 9771 # 0.557211 s
```

This VGM file is used as stimuli in verilator by running the command
```
./go -w -f ~/a3520.vgm
```

The generated waveform is analyzed using Audacity, and the result is:
1. The first sequence has a frequency of 1782 Hz.
2. The second sequence has a 0-100% attack time of 140 ms.

The expected result is that the frequency is 3520 Hz, whereas the attack time is correct.

[a3520.vgm.gz](https://github.com/jotego/jt51/files/4276221/a3520.vgm.gz)

**Comment by jotego** [comment]
Ok. I'll check that jtt file. After all I'm glad someone else has triggered my simulation setup!

**Comment by MJoergen** [comment]
Well, this turned out to be a user error.

The documentation clearly states that to generate a 440 Hz tone, the parameter MUL must be set to 1. I had set it to zero.

If I insert the register write $040,01 to the test, the frequency indeed does become 440 Hz.

So I'll close this issue, and go back to study the documentation some more ...

**Comment by jotego** [comment]
I'm glad you found it!
