### ISSUE TITLE
Checkout of MC6809 submodule fails

### ISSUE THREAD

**Issue by robinsonb5** [jotego/jt51#11]
Checking out the repo with git clone --recurse-submodules shows the following error messages in the shell:

Submodule path 'modules/jt51': checked out '48c12e2fcb2e03163423ca21cead995f41dd5978'
Submodule 'mc6809' (git@github.com:cavnex/mc6809.git) registered for path 'mc6809'
Cloning into 'mc6809'...
Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:cavnex/mc6809.git' into submodule path 'mc6809' failed

**Comment by jotego** [comment]
I have deleted that submodule. It's no longer needed. Thank you for reporting it.
