### ISSUE TITLE
Key ON event not received

### ISSUE THREAD

**Issue by MJoergen** [jotego/jt51#13]
The following JTT file yields no wave output:
```
$020,C7
$028,4A
$040,01
$060,00
$080,1F
$0A0,00
$0E0,FF
$008,08
$028,4A   # This is a duplicate (i.e. redundant) write
wait 1000
```

However, if I remove the last (duplicate) write to ```@028.4A``` (which could be any other write), then the expected waveform is generated (440 Hz sine wave @ -6 dB).

Likewise, if I insert a "wait 5" to the following:
```
$020,C7
$028,4A
$040,01
$060,00
$080,1F
$0A0,00
$0E0,FF
wait 5
$008,08
$028,4A   # This is a duplicate (i.e. redundant) write
wait 1000
```
then again the correct waveform is generated.

It appears (by viewing the signal waveform in the generated FST file) that the signal ```u_mmr.u_reg.u_kon.up_keyon``` indeed goes to 1 for some time, but then goes back to 0 just before ```u_mmr.u_reg.u_kon.cur_op_hot``` achieves the value 1.

**Comment by jotego** [comment]
This looks very interesting. I'll look into it. Thank you.

**Comment by jotego** [comment]
Fixed in commit https://github.com/jotego/jt51/commit/a0847ef5813cb2bd06cc696c4f842c696085a255
Thank you very much for the test case.
