### ISSUE TITLE
It is unclear what the GNU License means for FPGA design

### ISSUE THREAD

**Issue by hansfbaier** [jotego/jt51#22]
See the section "What is wrong with GPL for FPGA design?"
https://ohwr.org/project/cernohl/wikis/faq
Probably using one of the reciprocal CERN open hardware 
licenses would be equivalent to the GPL but much easier to interpret/use.

**Comment by jotego** [comment]
What will be a use case where this license is a problem?

**Comment by hansfbaier** [comment]
The main problem is that in the GNU license 'linking' means in the GPL.
For example if the JT51 core is on a FPGA board, which I then plug into the PC via USB,
then the FPGA-board is electrically linked to the PC.
In principle this is no different than the electrical link inside the FPGA to other cores there.
So if linking here means electrical connection, that would mean all the connected cores and the PC
would need all to be GPL too.

**Comment by hansfbaier** [comment]
Furthermore, the GPL would imply it is impossible to use it together in the same design  with a proprietary IP, for example a DDR memory controller using UniPHY on the Altera platform. Since there is currently no open source DDR memory controller available for Altera FPGAs, that would mean it would be impossible to use the JT51 in such a project.

**Comment by jotego** [comment]
GPL3 applies to elements designed to work exclusively with the licensed code. That's why you can run GPL3 software on a MacOS machine. 
You could connect the FPGA electrically to another element as long as that other element has a clear use outside the licensed code. 

For instance, a speaker or a PLL inside the FPGA. A softcore IP, such as a memory controller, in the same binary may need the same GPL3 license though.

I can provide special licenses for particular cases, including commercial and closed ones, though.

**Comment by hansfbaier** [comment]
That would mean, it would be impossible to use the JT51 on Intel/Altera FPGAs as soon DDR memory is used.
Because the Altera's wrapper code around their hard UniPHY is proprietary and encrypted, and has not been reverse engineered by the open source community yet.

**Comment by jotego** [comment]
Does that mean that you cannot use GPLv3 software on a Linux machine that uses a proprietary NVidia driver? I don't think that's the case. But I understand that if the UniPHY wrapper represents an ad-hoc customization for the project that uses JT51, then it needs to be disclosed too.
That wouldn't change with a CERN license either, it would still be the same case for the strong reciprocal license. I have read the CERN license and I don't see much difference other than the document length. The patent section isn't really relevant either.
I guess for the case of a physical DDRx driver on the FPGA, the wrapper will need to be open source too, as is the case for the PLL instantiation modules. Altera documentation should explain how to instantiate the primitives; so there is no need to reverse engineer anything, just make a fresh wrapper.

**Comment by hansfbaier** [comment]
Okay thank you very much for clarifying.
I think that should do.
