### ISSUE TITLE
Registers state at startup

### ISSUE THREAD

**Issue by fbelavenuto** [jotego/jt51#9]
Hi, testing your code in the MSX1FPGA with Double Dragon VGM, there are some troubles with initial state of some registers. If they are initialized all with 0xFF the song works.

I made a change in the jt51_reg.v for this:

```
--- jt51\jt51_reg.v	2017-12-07 10:17:14.000000000 -0300
+++ jt51\jt51_reg.v.orig	2018-09-27 10:44:35.706000000 -0300
@@ -218,15 +218,6 @@
 localparam opreg_w = 42;
 reg  [opreg_w-1:0] reg_op[31:0];
 reg  [opreg_w-1:0] reg_out;
-integer i;
-
-initial
-begin
-	for (i=0; i<32; i=i+1)
-	begin
-		reg_op[i] = ~0;
-	end
-end
 
 assign { dt1_II, mul_VI, tl_VII, ks_III, amsen_VII, 
 	dt2_I, d1l_I, arate_II, rate1_II, rate2_II, rrate_II  } = reg_out;
```

**Comment by jotego** [comment]
This is very interesting. I avoid initial values because somehow they tend to require more FPGA real state. I'll check this.
I have to update JT51 to make the CPU interface more robust, copying from JT12 v0.39. I'll do that soon and include your change too.

**Comment by jotego** [comment]
Please try again with the latest version in the repository and without your editing.
